name: Optimum common / Doctest
# Note: this test uses transformers stable and optimum dev

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 0 # every sunday at 1am

jobs:
  do-the-job:
    name: Start self-hosted EC2 runner
    runs-on:
      group: aws-g6-4xlarge-plus
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -f tests/onnxruntime/Dockerfile_onnxruntime_gpu -t onnxruntime-gpu .
      - name: Test with unittest within docker container
        run: |
          docker run --rm --gpus all --workdir=/workspace/optimum/ onnxruntime-gpu:latest /bin/bash tests/run_doctest.sh
