name: ONNX Runtime GPU / Python - Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 7 * * * # every day at 7am UTC
  pull_request:
    branches: [main]
    types:
      - opened
      - labeled
      - reopened
      - unlabeled
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains(github.event.pull_request.labels.*.name, 'gpu') ||
      contains(github.event.pull_request.labels.*.name, 'onnxruntime-gpu')
      }}

    runs-on:
      group: aws-g6-4xlarge-plus

    container:
      image: nvcr.io/nvidia/tensorrt:24.12-py3
      options: --gpus all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
          pip install .[tests,onnxruntime-gpu] diffusers

      - name: Test with pytest
        run: |
          pytest tests/onnxruntime -m "cuda_ep_test or trt_ep_test" --durations=0 -vvvv -n auto
