name: Optimum Pipelines / Python - Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: 1
  UV_TORCH_BACKEND: auto
  TRANSFORMERS_IS_CI: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        runs-on: [ubuntu-22.04]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip uv
          uv pip install --no-cache-dir optimum-onnx[onnxruntime]@git+https://github.com/huggingface/optimum-onnx.git
          uv pip install --no-cache-dir .[tests]

      - name: Test with pytest
        run: |
          pytest tests/pipelines -vvvv --durations=0
