name: Exporters / Test GPU

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 */3 * * # at 1am every 3 days
  pull_request:
    types: [labeled]
  # uncomment to enable on PR merge on main branch:
  #push:
  #  branches:
  #    - main

jobs:
  do-the-job:
    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule') || contains( github.event.pull_request.labels.*.name, 'gpu-test') }}
    name: Start self-hosted EC2 runner
    runs-on:
      group: aws-g6-4xlarge-plus
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -f tests/exporters/Dockerfile_exporters_gpu -t exporters-gpu .
      - name: Test with unittest within docker container
        run: |
          docker run --rm --gpus all -v /mnt/cache/.cache/huggingface:/root/.cache/huggingface --workdir=/workspace/optimum/tests exporters-gpu:latest
