name: Exporters Common / Python - Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  TRANSFORMERS_IS_CI: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-22.04]
        python-version: [3.9]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install optimum-onnx@git+https://github.com/huggingface/optimum-onnx.git
          pip install .[tests]

      - name: Test with pytest
        run: |
          pytest tests/exporters/common -vvvv --durations=0 -n auto
