name: BetterTransformer GPU / Python - Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 */3 * * # at 1am every 3 days

jobs:
  do-the-job:
    name: Start self-hosted EC2 runner
    runs-on:
      group: aws-g6-4xlarge-plus
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -f tests/bettertransformer/Dockerfile_bettertransformer_gpu -t bettertransformer-gpu .
      - name: Test with unittest within docker container
        run: |
          docker run --rm --gpus all --workdir=/workspace/optimum/tests bettertransformer-gpu:latest
