name: Utils / Python - Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13]
        python-version: ['3.9']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install .[tests]

      - name: Test with pytest
        working-directory: tests
        run: |
          pytest utils -s -n auto -m "not datasets_test" --durations=0

      - name: Install datasets
        run: |
          pip install datasets

      - name: Tests needing datasets
        working-directory: tests
        run: |
          pytest utils -s -n auto -m "datasets_test" --durations=0