name: Upload PR Documentation

on:
  workflow_run:
    workflows: ["Build PR documentation"]
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    uses: huggingface/doc-builder/.github/workflows/upload_pr_documentation.yml@9f9bb430a712b5650d0e43e510656098ecdd75d4  # main
    with:
      package_name: optimum
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
      comment_bot_token: ${{ secrets.COMMENT_BOT_TOKEN }}
